# Generated by Django 4.1.3 on 2022-12-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=40)),
                ('precio', models.IntegerField(max_length=6)),
                ('procedencia', models.CharField(max_length=40)),
            ],
        ),
    ]
