# Generated by Django 4.1.3 on 2022-12-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='edad',
            field=models.IntegerField(default='00', max_length=2),
        ),
    ]
